### ISSUE TITLE
SimulationArchives larger than 4GB

### ISSUE THREAD

**Issue by hannorein** [hannorein/rebound#666]
Currently 32 bit addresses are used to refer to positions in a SimulationArchive. This restricts the size to 4GB.

**Comment by hannorein** [comment]
I've just pushed a commit to the `largefiles` branch. @fhlobik Could you have a look of this was enough to get it working? I don't have a large archive to test it right now. Thank you!

**Comment by fhlobik** [comment]
Thank you, but it still doesn't seem to work. I'm getting the same results.

**Comment by hannorein** [comment]
Thanks. Look like I need to create my own 4GB file ;-)

**Comment by hannorein** [comment]
Could you try again on the same branch. I believe this should be working now.

**Comment by fhlobik** [comment]
At first it was giving `NameError: name 'c_uint64' is not defined. Did you mean: 'c_int64'?` line 57 in simulationarchive.py. After changing `c_uint64` to `c_int64` the simulation archives loaded properly. 
Thank you!

**Comment by hannorein** [comment]
Thanks for checking!

You were too fast! ;-). I had just fixed that error in the latest commit. 

Let me know if you encounter any problems. Otherwise I'll merge it into the main branch in a little while.
